### PR TITLE
Small adjustments to the Usage guide

### PR DESCRIPTION
**Pull request by mfbenitezp**
Small adjustments to the Usage guide, based on my testing on Turing Mac.

### CODE REVIEW

**Comment by dabreegster** [comment]
Thank you! There are a few typos in the docs, I'll push a commit and fix them. I'm also not sure why there are all these changes to `Cargo.lock` in this PR -- it looks like you were experimenting locally with pyo3 and a bunch of stuff. I'll revert those as well; let me know if anything there is important to keep.

**Comment by mfbenitezp** [comment]
Sorry for the typos I can fixed if you’d like. About the chances in Cargo.lock is bcs I added numpy then I read about your intentions of get ride of python in the near future so I removed it.

**Comment by dabreegster** [comment]
I already fixed the typos and merged, no worries!

The Rust code already does read the numpy format using a native Rust module called ndarray: https://github.com/dabreegster/spc/blob/52dfb317083e0d2d54b9050962cc96f40bf82f30/src/init/quant.rs#L71

The problem is that the QUANT tables aren't saved in the numpy format; they use python pickle instead. The "proper fix" here is to upload the numpy format to our Azure bucket directly. No need for everyone to have to run this conversion. But we should probably sync with Hadrien about the contents of the Azure bucket before changing anything.

**Comment by mfbenitezp** [comment]
OK, let see I guess there is no problem. But I guess we can also ask Kelin to figure it our our budget limit.

**Pull request merged**
